### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by mpacer** [slinderman/pyhawkes#2]
It looks like its just python2 compatible, if you're interested in making this python3 compatible (and it turns out to be as straightforward as it looks at first glance with only needing to tweak print statements), I'm happy to submit a PR.

**Comment by slinderman** [comment]
You're right, I haven't maintained Python3 standards. If you don't mind submitting a PR, that would be much appreciated! Otherwise I will get to it eventually.

**Comment by michaelpacer** [comment]
So if you look at the https://github.com/michaelpacer/pyhawkes/tree/futurizing branch you'll see that I've begun to do this (first with the futurize script), but then ran into some other problems with the way that different packages/submodules/modules are imported in gslrandom(https://github.com/slinderman/gslrandom/issues/4) and pybasicbayes(https://github.com/mattjj/pybasicbayes/issues/22). I see that these other packages need to be brought up to python3 compatibility, but I fear that I am in over my head at pushing all of these dependencies up to compatibility at the same time especially since there seem to be major infrastructural changes that are happening for most of these projects currently (e.g., the nonexistant internals module that was attempted to be imported by the setup.py in `pybasicbayes`).

I'm going to have to step away from this for a little while, since being able to move forward effectively requires having a working model of all the intricacies of these different parts playing together…including knowing which version of the structure can be expected from `pybasicbayes`… 

I don't know when I'll be able to start looking at incorporating some of this into [cbnx](https://github.com/michaelpacer/Causal-Bayesian-NetworkX), since its primarily built on python3 (I don't think I wrote it to be python2 compatible…but I could try pasteurizing it…but I don't want to be developing it in python2 and cbnx is still badly in need of further development).

**Comment by mattjj** [comment]
As you correctly assessed, many of the problems you're having stem from the fact that I reorganized pybasicbayes recently without really taking the time to make it backwards-compatible or warn anybody (or make sure the install still worked).

That said, I have some time to fix my mistakes now, so if you open issues (here or in pybasicbayes) for the problems you run into (e.g. pastes of import errors) I can probably clean things up pretty efficiently.

**Comment by slinderman** [comment]
It's been a long time, but I've finally gone ahead and updated pyhawkes for Python 3. Please see https://github.com/slinderman/pyhawkes/commit/843b5ed09ab4e32918a89c8ce43ccc7153a4109f and https://github.com/slinderman/pyhawkes/commit/091285c61e3480dceb3aded638ae27f0a921c6aa.
