### ISSUE TITLE
Installation issues on MAC OS X Yosemite

### ISSUE THREAD

**Issue by lecueguillaume** [slinderman/pyhawkes#4]
I've tried to install your library on MAC OS X with Python 2.7.10 (Anaconda 2.1.0 (x86_64)) following your instruction but it appears that I've several issues trying various examples. One of which is about the method plotting.plotting which does not work.
 
$ python test_sbm_gibbs.py 
Traceback (most recent call last):
  File "test_sbm_gibbs.py", line 9, in <module>
    from pyhawkes.plotting.plotting import plot_network
ImportError: No module named plotting.plotting

Could you please tell me how to fix that ?

Thanks,
Guillaume.

**Comment by slinderman** [comment]
Hi Guillaume,
Thanks for pointing this out. Those "tests" are a bit old and out of date. They were really just for debugging during development, but they might prove useful if you're interested in playing with stochastic block models for the network. I just updated `test_sbm_gibbs.py` so that it will run. See https://github.com/slinderman/pyhawkes/commit/e2b9a47f468bb7d6c3c45b3d70257e8166228d4e
and https://github.com/slinderman/pyhawkes/commit/01cee2f9f0cd8ead5018c1bffd7fe8e5f0a4ab26.

Also, check out the `examples` directory for some more polished demos.  

Best,
Scott
